# Generated by Django 5.2.17 on 2026-08-30 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_category_locationdiscount_product_gender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryServiceArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('center_latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('center_longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('radius_km', models.DecimalField(decimal_places=2, default=50, max_digits=6)),
                ('delivery_days_min', models.PositiveSmallIntegerField(default=3)),
                ('delivery_days_max', models.PositiveSmallIntegerField(default=6)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PincodeLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pincode', models.CharField(max_length=20, unique=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, default='India', max_length=100)),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_serviceable', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='locationdiscount',
            name='code',
            field=models.CharField(blank=True, help_text='Optional coupon code shown to shoppers, e.g. DELHI20. Leave blank for an unnamed discount.', max_length=40, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='locationdiscount',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='locationdiscount',
            name='minimum_order_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='locationdiscount',
            name='title',
            field=models.CharField(blank=True, help_text="Short display name, e.g. 'Delhi Special Offer'.", max_length=120),
        ),
        migrations.AddField(
            model_name='locationdiscount',
            name='usage_limit',
            field=models.PositiveIntegerField(blank=True, help_text='Total number of times this coupon may be used. Leave blank for unlimited.', null=True),
        ),
        migrations.AddField(
            model_name='locationdiscount',
            name='used_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='coupon_code',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
