# Generated by Django 5.2.17 on 2026-08-30 19:42

import django.db.models.deletion
import store.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_deliveryservicearea_pincodelocation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pincodelocation',
            name='is_serviceable',
        ),
        migrations.AddField(
            model_name='address',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='address',
            name='label',
            field=models.CharField(blank=True, default='', help_text='e.g. Home, Office, Other', max_length=30),
        ),
        migrations.CreateModel(
            name='CustomizationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customization_type', models.CharField(choices=[('design', 'Design Your Own Jewelry'), ('engraving', 'Engraving Services'), ('birthstone', 'Birthstone Jewelry'), ('name', 'Name Necklaces'), ('photo', 'Photo Jewelry')], default='design', max_length=20)),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('description', models.TextField(help_text='Customization details / instructions from the shopper.')),
                ('reference_image', models.ImageField(blank=True, null=True, upload_to=store.models.customization_image_upload_path)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('in_review', 'In Review'), ('approved', 'Approved'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(blank=True, help_text='Existing product this request is based on, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customization_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
