# Generated by Django 5.2.17 on 2026-08-31 10:55

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_pincodelocation_is_serviceable_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed')], max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('minimum_order_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('maximum_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('usage_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('used_count', models.PositiveIntegerField(default=0)),
                ('per_user_limit', models.PositiveIntegerField(default=1)),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
                ('first_order_only', models.BooleanField(default=False)),
                ('applicable_country', models.CharField(blank=True, max_length=100)),
                ('applicable_state', models.CharField(blank=True, max_length=100)),
                ('applicable_city', models.CharField(blank=True, max_length=100)),
                ('applicable_pincode', models.CharField(blank=True, max_length=10)),
                ('minimum_delivery_radius_km', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('maximum_delivery_radius_km', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='customizationrequest',
            options={},
        ),
        migrations.RemoveField(
            model_name='address',
            name='is_default',
        ),
        migrations.RemoveField(
            model_name='address',
            name='label',
        ),
        migrations.RemoveField(
            model_name='customizationrequest',
            name='customization_type',
        ),
        migrations.RemoveField(
            model_name='locationdiscount',
            name='code',
        ),
        migrations.RemoveField(
            model_name='locationdiscount',
            name='description',
        ),
        migrations.RemoveField(
            model_name='locationdiscount',
            name='minimum_order_amount',
        ),
        migrations.RemoveField(
            model_name='locationdiscount',
            name='title',
        ),
        migrations.RemoveField(
            model_name='locationdiscount',
            name='usage_limit',
        ),
        migrations.RemoveField(
            model_name='locationdiscount',
            name='used_count',
        ),
        migrations.AddField(
            model_name='customizationrequest',
            name='budget_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='customizationrequest',
            name='budget_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='deliveryservicearea',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliveryservicearea',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='order',
            name='coupon_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_days_max',
            field=models.PositiveSmallIntegerField(default=6),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_days_min',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='order',
            name='serviceability_checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pincodelocation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pincodelocation',
            name='is_serviceable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customizationrequest',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='customizationrequest',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='customizationrequest',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customization_requests', to='store.product'),
        ),
        migrations.AlterField(
            model_name='customizationrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='deliveryservicearea',
            name='radius_km',
            field=models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='order',
            name='coupon_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pincodelocation',
            name='city',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='pincodelocation',
            name='country',
            field=models.CharField(default='India', max_length=100),
        ),
        migrations.AlterField(
            model_name='pincodelocation',
            name='district',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='pincodelocation',
            name='pincode',
            field=models.CharField(db_index=True, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='pincodelocation',
            name='raw_response',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='pincodelocation',
            name='state',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.CreateModel(
            name='CouponUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='store.coupon')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('coupon', 'user', 'order'), name='unique_coupon_user_order')],
            },
        ),
    ]
