# Generated by Django 5.2.17 on 2026-09-08 06:44

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_supportticket_supportmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customizationrequest',
            name='reference_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='reference_image'),
        ),
    ]
